### ISSUE TITLE
Committed number of lines does not match the number of transcribed lines

### ISSUE THREAD

**Issue by wrznr** [jbaiter/archiscribe-corpus#1]
I just checked the tool and transcribed two lines.  After saving, the commit messages states that 50 lines have been delivered. Sorry, if I “abused” the tool.

**Comment by jbaiter** [comment]
No abuse at all, just regular usage that uncovered a bug :-)
It's supposed to be a feature that you can submit at any time and the API should filter out all non-transcribes lines. Working on it!

BTW, I don't think the IA has many books with colored pages, since the bulk of the corpus was scraped from Google Books.
